#
# Generated by: @@GENERATED_BY@@
#

function simpleFunction()
{
    echo @@SIMPLE_VAR@@
}

#
# watch the difference between using the heredoc returned by the
# _getTemplate() function, and using the _getAssetFile(): in the second
# case, hello var is not evaluated
#
echo "The following var is a bash var: $hello"

@@CMD_PLACEHOLDER@@
