
source $(dirname $(realpath ${BASH_SOURCE[0]}))"/../vendor/autoload.sh"

function Example1_run()
{
    local hello='hellobashvar'

    local myTemplate=$(Example1_getTemplate)

    MiniTemplateEngine_dataProvider=(
        @@GENERATED_BY@@="${BASH_SOURCE[0]}"
        @@SIMPLE_VAR@@="Template Hello"
        @@CMD_PLACEHOLDER@@="simpleFunction"
    )
    local tplOut=$(MiniTemplateEngine_process "$myTemplate")
    echo "$tplOut"
}

function Example2_run()
{
    local hello='hellobashvar'

    local myTemplate=$(MiniTemplateEngine_getAssetFile "templateExample.sh")

    MiniTemplateEngine_dataProvider=(
        @@GENERATED_BY@@="${BASH_SOURCE[0]}"
        @@SIMPLE_VAR@@="Template Hello"
        @@CMD_PLACEHOLDER@@="simpleFunction"
    )
    local tplOut=$(MiniTemplateEngine_process "$myTemplate")
    echo "$tplOut"
}

function Example3_run()
{
    local tplOut=$(MiniTemplateEngine_process "$myTemplate")
    echo "Undeclared dataProvider returns empty string"
    echo "$tplOut"

    if MiniTemplateEngine_dataProviderEmpty ; then
        echo "The dataProvider is empty or not defined"
    fi
}

#######################
# private
#######################

function Example1_getTemplate()
{
    cat<<'EOF'
#
# Generated by: @@GENERATED_BY@@
#

function simpleFunction()
{
    echo @@SIMPLE_VAR@@
}

#
# watch the difference between using the heredoc returned by the
# _getTemplate() function, and using the _getAssetFile(): in the second
# case, hello var is not evaluated
#
echo "The following var is a bash var: $hello"

@@CMD_PLACEHOLDER@@
EOF
}

Example1_run
#Example2_run
#Example3_run
