parameters:
#    rivestlab_car.example.class: Rivestlab\CarBundle\Example

services:
#    rivestlab_car.example:
#        class: %rivestlab_car.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
